#This configuration file holds all the common configs to be shared among other microservices
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/userinfo/user/current
      token-info-uri: http://localhost:8080/userinfo/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG

hytrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000